USE [master]
GO

/****** Object:  Database [EventStore]    Script Date: 01/02/2013 20:01:08 ******/
CREATE DATABASE [EventStore] ON  PRIMARY 
( NAME = N'EventStore', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\EventStore.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'EventStore_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\EventStore_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [EventStore] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EventStore].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EventStore] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EventStore] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EventStore] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EventStore] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EventStore] SET ARITHABORT OFF 
GO

ALTER DATABASE [EventStore] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EventStore] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [EventStore] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EventStore] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EventStore] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EventStore] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EventStore] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EventStore] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EventStore] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EventStore] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EventStore] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EventStore] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EventStore] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EventStore] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EventStore] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EventStore] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EventStore] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EventStore] SET  READ_WRITE 
GO

ALTER DATABASE [EventStore] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [EventStore] SET  MULTI_USER 
GO

ALTER DATABASE [EventStore] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EventStore] SET DB_CHAINING OFF 
GO

USE [EventStore]
GO
/****** Object:  Table [dbo].[Events]    Script Date: 01/02/2013 20:00:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Events](
	[Id] [uniqueidentifier] NOT NULL,
	[AggregateId] [uniqueidentifier] NOT NULL,
	[Version] [int] NOT NULL,
	[Event] [xml] NOT NULL
) ON [PRIMARY]
GO
